name: Deploy Nuxt.js Blog to Cloudflare Pages

# Trigger the workflow on every push to any branch
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Set permissions for the workflow
permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund

      # Step 4: Build the static site
      - name: Build static site
        run: npm run generate
        env:
          NODE_ENV: production

      # Step 5: Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME || 'brainsait-blog' }} --compatibility-date=2025-07-03

      # Step 6: Output deployment info
      - name: Output deployment info
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🚀 Your BrainSAIT blog is live at: https://${{ secrets.CLOUDFLARE_PROJECT_NAME || 'brainsait-blog' }}.pages.dev"
