name: Deploy Nuxt.js Blog to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Remove cache until package-lock.json exists
          # cache: 'npm'
          # cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: |
          # Check if package.json exists
          if [ -f "package.json" ]; then
            echo "📦 Installing dependencies..."
            npm ci --prefer-offline --no-audit --no-fund
          else
            echo "❌ No package.json found. Creating basic Nuxt.js project..."
            npm init -y
            npm install nuxt@latest
            
            # Create basic nuxt.config.ts
            cat > nuxt.config.ts << 'EOF'
export default defineNuxtConfig({
  devtools: { enabled: true },
  nitro: {
    preset: 'cloudflare-pages'
  },
  app: {
    head: {
      title: 'BrainSAIT Healthcare Analytics Blog',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Healthcare data analysis and insurance sector insights by BrainSAIT' }
      ]
    }
  }
})
EOF
            
            # Create basic app.vue
            mkdir -p pages
            cat > app.vue << 'EOF'
<template>
  <div>
    <h1>🏥 BrainSAIT Healthcare Analytics Blog</h1>
    <p>Welcome to our healthcare data analysis and insurance sector insights platform.</p>
    <p>Specializing in Swift, Python, and modern web technologies.</p>
  </div>
</template>
EOF
            
            # Update package.json scripts
            npm pkg set scripts.generate="nuxt generate"
            npm pkg set scripts.build="nuxt build"
            npm pkg set scripts.dev="nuxt dev"
            npm pkg set scripts.preview="nuxt preview"
          fi

      - name: Build static site
        run: |
          echo "🔨 Building Nuxt.js static site..."
          npm run generate
        env:
          NODE_ENV: production

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME || 'brainsait-blog' }} --compatibility-date=2025-07-03

      - name: Output deployment info
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🚀 Your BrainSAIT blog is live at: https://${{ secrets.CLOUDFLARE_PROJECT_NAME || 'brainsait-blog' }}.pages.dev"
          echo "🏥 Perfect for healthcare data analysis content!"
